[package]
name = "riscv"
version = "0.1.0"
authors = ["Felix Prasanna <fpx@mit.edu>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
parse_int = "0.6.0"
anyhow = "1.0.72"
thiserror = "1.0.44"
indoc = "2.0.3"
